### ISSUE TITLE
Class 'League\CommonMark\Environment' not found

### ISSUE THREAD

**Issue by proghasan** [vanguardapp/announcements#6]
After composer update or install 
`Class 'League\CommonMark\Environment' not found`

**Comment by loshmis** [comment]
Make sure that you are fetching the latest version of this plugin (v3.0.2 at the moment) which contains [the fix](https://github.com/vanguardapp/announcements/commit/4fa0e55ab09e83dc49aa0ace5d63bba92d269d38) for this issue. 
The latest version of Vanguard already uses v3.0.2 but if you are using some of the previous Vanguard versions, you'll need to update the composer manually.

**Comment by proghasan** [comment]
Thank you work now
